### ISSUE TITLE
ENH: support exporting

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/portable-fs#2]
If we want to use portable filestore as a bridge between the NSLS and home institution databrokers (using mongo backends) we need a way for portable filestore to export data.

Example workflow
NSLS_DB -> Portable_MDS/Portable_FS (on external disk) -> Home_DB (using Mongo)

**Comment by ghost** [comment]
@danielballan has done a significant amount of work to ensure the APIs for portable and persistent FS (and MDS) are identical so the workflow you are describing is already possible using the correct singletons. If you are talking about `export(target, destination)`, we don't have that in fs/mds.
We have json support for portable-mds, so you could simply import the json file into your mongo instance without using our APIs at all.

**Comment by CJ-Wright** [comment]
I was under the impression that the exporting features recently pulled into filestore have not been implemented in the portable version. For example does the portable filestore correctly move files to a different folder and track that?

**Comment by danielballan** [comment]
Yes, @CJ-Wright is correct: unfortunately in this case the APIs are not identical. The filestore API got ahead of the portable_fs API here. The following methods, recently added to filestore, now need to be added to portable_fs:
- resource_given_eid
- copy_files
- datum_gen_given_resource

Do either of you have the bandwidth to implement analogous methods in portable-fs? I would target the sqlite variant first.

**Comment by CJ-Wright** [comment]
I'll try to take a crack at it.
